In [20]:
import pandas as pd  
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [21]:
dataset = pd.read_csv('bill_authentication.csv') 

In [22]:
dataset.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [23]:
print("checking if any null values are present\n", dataset.isna().sum())

checking if any null values are present
 Variance    0
Skewness    0
Curtosis    0
Entropy     0
Class       0
dtype: int64


In [24]:
dataset.tail()

Variance  Skewness  Curtosis  Entropy  Class
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

In [25]:
train_cols = ["Variance","Skewness","Curtosis","Entropy"]

In [26]:
Label_cols = ["Class"]

In [27]:
df_train, df_test = train_test_split(dataset, train_size=0.8, test_size=0.2, shuffle=True)

In [28]:
# Training set
X_train = df_train.loc[:,train_cols].values
y_train = df_train.loc[:,Label_cols].values

In [29]:
X_train

array([[-1.42170e+00,  1.16542e+01, -5.76990e-02, -7.10250e+00],
       [ 3.77910e+00,  2.57620e+00,  1.30980e+00,  5.65500e-01],
       [-1.68200e+00, -6.81210e+00,  7.13980e+00,  1.33230e+00],
       ...,
       [-2.90200e+00, -7.65630e+00,  1.18318e+01, -8.42680e-01],
       [ 1.93400e+00, -9.28280e-06,  4.81600e+00, -3.39670e-01],
       [-2.48240e+00, -7.30460e+00,  6.83900e+00, -5.90530e-01]])

In [30]:
# Test set
X_test = df_test.loc[:,train_cols].values
y_test = df_test.loc[:,Label_cols].values

In [31]:
# Normalizing data
sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

In [32]:
Classifier = RandomForestClassifier(n_estimators=20, random_state=0)  
Classifier.fit(X_train, y_train)  
y_pred = Classifier.predict(X_test) 


c:\users\rajesh\appdata\local\programs\python\python35\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


In [33]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))  

[[148   1]
 [  0 126]]
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       149
           1       0.99      1.00      1.00       126

   micro avg       1.00      1.00      1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275

0.9963636363636363


In [34]:
Classifier = RandomForestClassifier(n_estimators=1000, random_state=0)  
Classifier.fit(X_train, y_train)  
y_pred = Classifier.predict(X_test) 

c:\users\rajesh\appdata\local\programs\python\python35\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


In [35]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred)) 


[[148   1]
 [  1 125]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       149
           1       0.99      0.99      0.99       126

   micro avg       0.99      0.99      0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275

0.9927272727272727
